from __future__ import annotations

from io import BytesIO

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt


class DOCXGenerator:
    content_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

    def generate(self, title: str, sections: list[tuple[str, str]]) -> bytes:
        document = Document()
        section = document.sections[0]
        section.top_margin = Inches(0.65)
        section.bottom_margin = Inches(0.65)
        section.left_margin = Inches(0.75)
        section.right_margin = Inches(0.75)

        styles = document.styles
        styles["Normal"].font.name = "Aptos"
        styles["Normal"].font.size = Pt(10.5)
        title_paragraph = document.add_heading(title, 0)
        title_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        subtitle = document.add_paragraph("Generated by CEASER")
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        subtitle.runs[0].font.size = Pt(9)
        subtitle.runs[0].font.italic = True

        for heading, body in sections:
            document.add_heading(heading, level=1)
            for paragraph in body.split("\n"):
                text = paragraph.strip()
                if not text:
                    continue
                if text.startswith("- "):
                    document.add_paragraph(text[2:].strip(), style="List Bullet")
                elif self._looks_numbered(text):
                    document.add_paragraph(text, style="List Number")
                else:
                    p = document.add_paragraph(text)
                    p.paragraph_format.space_after = Pt(6)
        buffer = BytesIO()
        document.save(buffer)
        return buffer.getvalue()

    @staticmethod
    def _looks_numbered(text: str) -> bool:
        return len(text) > 2 and text[0].isdigit() and text[1] in {".", ")"}
