from __future__ import annotations

from io import BytesIO
import textwrap

import fitz


class PDFGenerator:
    content_type = "application/pdf"

    def generate(self, title: str, sections: list[tuple[str, str]]) -> bytes:
        document = fitz.open()
        page = document.new_page()
        y = 52
        y = self._write(page, title, 48, y, 20, bold=True)
        y = self._write(page, "Generated by CEASER", 48, y + 2, 9)
        for heading, body in sections:
            if y > 700:
                page = document.new_page()
                y = 56
            y = self._write(page, heading, 48, y + 16, 14, bold=True)
            for line in body.splitlines():
                text = line.strip()
                if not text:
                    continue
                prefix = "- " if text.startswith("- ") else ""
                text = text[2:].strip() if prefix else text
                for wrapped in textwrap.wrap(text, width=92) or [""]:
                    if y > 760:
                        page = document.new_page()
                        y = 56
                    y = self._write(page, f"{prefix}{wrapped}", 56 if prefix else 48, y + 3, 10)
                    prefix = "  " if prefix else ""
            y += 4
        return document.tobytes()

    def _write(self, page, text: str, x: int, y: int, size: int, bold: bool = False) -> int:
        font = "helv"
        page.insert_textbox(fitz.Rect(x, y, 545, y + 72), text, fontsize=size, fontname=font, color=(0.05, 0.07, 0.12))
        return y + (30 if bold else 15)
