from __future__ import annotations

from io import BytesIO

from pptx import Presentation
from pptx.util import Pt


class PPTXGenerator:
    content_type = "application/vnd.openxmlformats-officedocument.presentationml.presentation"

    def generate(self, title: str, sections: list[tuple[str, str]]) -> bytes:
        presentation = Presentation()
        title_slide = presentation.slides.add_slide(presentation.slide_layouts[0])
        title_slide.shapes.title.text = title
        title_slide.placeholders[1].text = "Generated by CEASER"
        for heading, body in sections:
            slide = presentation.slides.add_slide(presentation.slide_layouts[1])
            slide.shapes.title.text = heading
            frame = slide.placeholders[1].text_frame
            frame.clear()
            for index, bullet in enumerate(self._slide_bullets(body)):
                paragraph = frame.paragraphs[0] if index == 0 else frame.add_paragraph()
                paragraph.text = bullet
                paragraph.level = 0
                paragraph.font.size = Pt(20 if index < 3 else 18)
        buffer = BytesIO()
        presentation.save(buffer)
        return buffer.getvalue()

    @staticmethod
    def _slide_bullets(body: str) -> list[str]:
        bullets = []
        for line in body.splitlines():
            text = line.strip()
            if not text:
                continue
            if text.startswith("- "):
                text = text[2:].strip()
            bullets.append(text)
            if len(bullets) == 5:
                break
        return bullets or ["Key point", "Recommendation", "Next step"]
