from __future__ import annotations

from io import BytesIO

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


class XLSXGenerator:
    content_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

    def generate(self, title: str, sections: list[tuple[str, str]]) -> bytes:
        workbook = Workbook()
        sheet = workbook.active
        sheet.title = self._sheet_name(title)

        column_count = max(2, len(sections))
        sheet.append([title])
        sheet.merge_cells(start_row=1, start_column=1, end_row=1, end_column=column_count)
        sheet["A1"].font = Font(bold=True, size=16, color="FFFFFF")
        sheet["A1"].fill = PatternFill("solid", fgColor="4F46E5")
        sheet["A1"].alignment = Alignment(horizontal="center")
        sheet.append(["Generated by CEASER"])
        sheet.merge_cells(start_row=2, start_column=1, end_row=2, end_column=column_count)
        sheet["A2"].font = Font(italic=True, color="64748B")

        headers = [heading for heading, _ in sections] or ["Item", "Notes"]
        sheet.append(headers)
        for cell in sheet[3]:
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = PatternFill("solid", fgColor="111827")
            cell.alignment = Alignment(wrap_text=True, vertical="top")

        max_rows = max((len(self._lines(body)) for _, body in sections), default=1)
        for index in range(max_rows):
            row = []
            for _, body in sections:
                lines = self._lines(body)
                row.append(lines[index] if index < len(lines) else "")
            sheet.append(row)

        sheet.freeze_panes = "A4"
        for column_index, _ in enumerate(headers, start=1):
            letter = get_column_letter(column_index)
            sheet.column_dimensions[letter].width = 26
            for cell in sheet[letter]:
                cell.alignment = Alignment(wrap_text=True, vertical="top")

        buffer = BytesIO()
        workbook.save(buffer)
        return buffer.getvalue()

    @staticmethod
    def _lines(body: str) -> list[str]:
        return [line.strip().lstrip("-•").strip() for line in body.splitlines() if line.strip()]

    @staticmethod
    def _sheet_name(title: str) -> str:
        safe = "".join(char for char in title if char not in r"[]:*?/\\").strip()
        return (safe or "CEASER")[:31]
