import {
  BarChart3,
  Brain,
  BrainCircuit,
  Code2,
  FileText,
  FolderKanban,
  GraduationCap,
  LayoutDashboard,
  MessageSquare,
  Puzzle,
  Search,
  Settings,
  User,
  Users,
  Zap,
} from "lucide-react"
import type {
  CeaserAgent,
  CeaserEngine,
  CeaserIntegration,
  NavigationItem,
} from "./types"

export const ceaserUser = {
  name: "Akshay",
  role: "Founder",
  avatar: "/avatar.jpg",
}

export const ceaserAgents: CeaserAgent[] = [
  {
    id: "ceaser",
    name: "CEASER",
    role: "Master Orchestrator",
    description: "Understands intent, retrieves context, routes agents, coordinates workflows, and aggregates results.",
    purpose: "Unified intelligence layer for the AI workforce.",
    status: "active",
    color: "#00d4ff",
    colorClass: "text-[#00d4ff]",
    bgColorClass: "bg-[#00d4ff]",
    icon: Brain,
    currentTask: "Orchestrating CEASER context and agent routing",
    progress: 92,
    modules: [
      { id: "intent", name: "Intent Understanding", description: "Understands user requests and desired outcomes." },
      { id: "context", name: "Context Management", description: "Maintains short-term and user context." },
      { id: "routing", name: "Agent Routing", description: "Selects the right agent and execution engine." },
      { id: "memory", name: "Memory Retrieval", description: "Fetches relevant long-term and semantic memory." },
      { id: "aggregation", name: "Result Aggregation", description: "Combines agent outputs into one answer." },
    ],
    capabilities: ["Intent understanding", "Context management", "Agent routing", "Memory retrieval", "Workflow coordination"],
  },
  {
    id: "bolt",
    name: "Bolt",
    role: "Operations & Execution Agent",
    description: "Executes work, coordinates workflows, manages tasks, and keeps operations moving.",
    purpose: "Execute work and coordinate workflows.",
    status: "active",
    color: "#00d4ff",
    colorClass: "text-[#00d4ff]",
    bgColorClass: "bg-[#00d4ff]",
    icon: Zap,
    currentTask: "Coordinating tasks and follow-ups",
    progress: 80,
    modules: [
      { id: "tasks", name: "Tasks", description: "Task management and tracking." },
      { id: "scheduling", name: "Scheduling", description: "Calendar-aware scheduling support." },
      { id: "reminders", name: "Reminders", description: "Reminder systems and alerts." },
      { id: "automation", name: "Workflow Planning", description: "Planning repeatable workflows." },
      { id: "workflow-execution", name: "Workflow Execution", description: "Execution of multi-step workflows." },
      { id: "follow-ups", name: "Follow-Ups", description: "Follow-up tracking and nudges." },
    ],
    capabilities: ["Tasks", "Scheduling", "Reminders", "Workflow planning", "Follow-ups"],
  },
  {
    id: "alex",
    name: "Alex",
    role: "Personal Life Intelligence Agent",
    description: "Manages goals, learning, productivity, health, travel, and personal finance intelligence.",
    purpose: "Personal growth and life management.",
    status: "idle",
    color: "#c084fc",
    colorClass: "text-[#c084fc]",
    bgColorClass: "bg-[#c084fc]",
    icon: User,
    currentTask: "Reviewing goals and productivity rhythm",
    modules: [
      { id: "goals", name: "Goals", description: "Personal goal tracking and planning." },
      { id: "productivity", name: "Productivity", description: "Focus and time management." },
      { id: "learning", name: "Learning", description: "Skill development and courses." },
      { id: "health", name: "Health", description: "Fitness, wellness, and habits." },
      { id: "travel", name: "Travel", description: "Trip planning and logistics." },
      { id: "finance", name: "Finance", description: "Personal budgeting and expenses." },
    ],
    capabilities: ["Goals", "Productivity", "Learning", "Health", "Travel", "Finance"],
  },
  {
    id: "friday",
    name: "Friday",
    role: "Communications & Content Agent",
    description: "Creates and manages communication, social content, campaigns, blogs, and email workflows.",
    purpose: "Content creation and communication.",
    status: "active",
    color: "#f59e0b",
    colorClass: "text-[#f59e0b]",
    bgColorClass: "bg-[#f59e0b]",
    icon: MessageSquare,
    currentTask: "Preparing content calendar and publishing queue",
    progress: 40,
    modules: [
      { id: "instagram", name: "Instagram", description: "Instagram content and scheduling." },
      { id: "linkedin", name: "LinkedIn", description: "LinkedIn posts and networking." },
      { id: "youtube", name: "YouTube", description: "YouTube video content." },
      { id: "blog", name: "Blog", description: "Blog writing and SEO." },
      { id: "email", name: "Email", description: "Email campaigns and newsletters." },
      { id: "content-planning", name: "Content Planning", description: "Editorial calendar and strategy." },
    ],
    capabilities: ["Instagram", "LinkedIn", "YouTube", "Blog", "Email", "Content planning"],
  },
  {
    id: "zeus",
    name: "Zeus",
    role: "Business Intelligence Agent",
    description: "Runs startup intelligence across strategy, technology, finance, operations, growth, analytics, and HR.",
    purpose: "Business operations and startup intelligence.",
    status: "active",
    color: "#fbbf24",
    colorClass: "text-[#fbbf24]",
    bgColorClass: "bg-[#fbbf24]",
    icon: BarChart3,
    currentTask: "Analyzing growth strategy and operating priorities",
    progress: 75,
    modules: [
      { id: "ceo", name: "CEO", description: "Strategy, decisions, and planning." },
      { id: "cto", name: "CTO", description: "Technology strategy and architecture." },
      { id: "cfo", name: "CFO", description: "Finance, budgeting, and forecasting." },
      { id: "coo", name: "COO", description: "Operations, processes, and SOPs." },
      { id: "marketing", name: "Marketing", description: "Growth, branding, and campaigns." },
      { id: "sales", name: "Sales", description: "Leads, pipeline, and conversion." },
      { id: "analytics", name: "Analytics", description: "Reports, KPIs, and insights." },
      { id: "hr", name: "HR", description: "Hiring, team, and performance." },
    ],
    capabilities: ["CEO", "CTO", "CFO", "COO", "Marketing", "Sales", "Analytics", "HR"],
  },
  {
    id: "nova",
    name: "Nova",
    role: "Research Intelligence Agent",
    description: "Performs deep research, competitor analysis, market research, trend monitoring, and reports.",
    purpose: "Knowledge gathering and analysis.",
    status: "active",
    color: "#a855f7",
    colorClass: "text-[#a855f7]",
    bgColorClass: "bg-[#a855f7]",
    icon: Search,
    currentTask: "Researching healthcare IT competitors and market signals",
    progress: 60,
    modules: [
      { id: "research", name: "Research", description: "Deep research on any topic." },
      { id: "competitor-analysis", name: "Competitor Analysis", description: "Track and analyze competitors." },
      { id: "market-research", name: "Market Research", description: "Market trends and opportunities." },
      { id: "trend-monitoring", name: "Trend Monitoring", description: "Industry trends and news." },
      { id: "reports", name: "Reports", description: "Generate detailed reports." },
    ],
    capabilities: ["Research", "Competitor analysis", "Market research", "Trend monitoring", "Reports"],
  },
  {
    id: "atlas",
    name: "Atlas",
    role: "Software Engineering Agent",
    description: "Builds software products through conversation from planning to architecture, coding, deployment, and GitHub management.",
    purpose: "Build software products through conversation.",
    status: "idle",
    color: "#6366f1",
    colorClass: "text-[#6366f1]",
    bgColorClass: "bg-[#6366f1]",
    icon: Code2,
    currentTask: "Waiting for software build instructions",
    modules: [
      { id: "planning", name: "Planning", description: "Product planning and requirements." },
      { id: "architecture", name: "Architecture", description: "System design and technical plans." },
      { id: "coding", name: "Coding", description: "Create and modify code." },
      { id: "infrastructure", name: "Infrastructure", description: "Cloud and system infrastructure." },
      { id: "devops", name: "DevOps", description: "CI/CD and deployment operations." },
      { id: "debugging", name: "Debugging", description: "Find and fix bugs." },
      { id: "code-review", name: "Code Review", description: "Review and improve code." },
      { id: "deployment", name: "Deployment", description: "Ship projects to hosting platforms." },
      { id: "github-management", name: "GitHub Management", description: "Repositories, commits, branches, and pushes." },
      { id: "vscode-integration", name: "VS Code Integration", description: "Editor-aware coding workflows." },
    ],
    capabilities: ["Planning", "Architecture", "Coding", "Infrastructure", "DevOps", "Debugging", "Code review", "Deployment", "GitHub", "VS Code"],
  },
]

export const ceaserIntegrations: CeaserIntegration[] = [
  { id: "github", name: "GitHub", category: "development", description: "Repository creation, commits, branches, and pushes.", status: "available" },
  { id: "vscode", name: "VS Code Extension", category: "development", description: "Editor-aware software building workflows.", status: "planned" },
  { id: "vercel", name: "Vercel", category: "deployment", description: "Frontend deployment and preview environments.", status: "available" },
  { id: "railway", name: "Railway", category: "deployment", description: "Backend and service deployment.", status: "available" },
  { id: "supabase", name: "Supabase", category: "data", description: "Authentication, database, and app storage foundation.", status: "available" },
  { id: "google-drive", name: "Google Drive", category: "productivity", description: "File storage and generated document sync.", status: "available" },
  { id: "gmail", name: "Gmail", category: "productivity", description: "Email communication and campaign workflows.", status: "available" },
  { id: "google-calendar", name: "Google Calendar", category: "productivity", description: "Events, scheduling, and reminders.", status: "connected" },
  { id: "notion", name: "Notion", category: "productivity", description: "Knowledge pages and notes.", status: "available" },
  { id: "deepgram", name: "Deepgram", category: "voice", description: "Speech-to-text for Voice.", status: "planned" },
  { id: "elevenlabs", name: "ElevenLabs", category: "voice", description: "Text-to-speech for CEASER responses.", status: "planned" },
]

export const ceaserEngines: CeaserEngine[] = [
  {
    id: "atlas",
    name: "Atlas Engine",
    purpose: "Universal software creation engine.",
    workflow: ["Idea", "Requirements", "Architecture", "Project plan", "Code generation", "Testing", "Deployment"],
    capabilities: ["Create projects", "Create files", "Modify files", "Read codebases", "Run commands", "Create repositories", "Commit code", "Push code", "Deploy projects"],
    integrations: ["vscode", "github", "vercel", "railway", "supabase"],
  },
  {
    id: "document",
    name: "Document Engine",
    purpose: "Universal document creation engine.",
    workflow: ["Research", "Content", "Charts", "Images", "Generation", "Review", "Conversational editing", "Export"],
    capabilities: ["PPTX generation", "DOCX generation", "XLSX generation", "PDF export", "Conversational edits"],
    integrations: ["google-drive"],
  },
  {
    id: "automation",
    name: "Automation Engine",
    purpose: "Execute workflows automatically.",
    workflow: ["Trigger", "Context retrieval", "Agent routing", "Execution", "Result logging"],
    capabilities: ["Daily summaries", "Weekly reports", "Content scheduling", "Research monitoring", "Reminder systems"],
    integrations: ["gmail", "google-calendar", "notion"],
  },
  {
    id: "memory",
    name: "Memory Engine",
    purpose: "Persistent intelligence across conversations, projects, goals, files, decisions, and activity.",
    workflow: ["Capture", "Store", "Link", "Retrieve", "Reason"],
    capabilities: ["Short-term memory", "Long-term memory", "Semantic memory", "Knowledge graph"],
  },
  {
    id: "voice",
    name: "Voice Engine",
    purpose: "Voice interaction with idle, listening, thinking, and speaking states.",
    workflow: ["Idle", "Listening", "Thinking", "Speaking"],
    capabilities: ["Speech-to-text", "Text-to-speech", "Voice commands", "Briefings"],
    integrations: ["deepgram", "elevenlabs"],
  },
]

export const navigationItems: NavigationItem[] = [
  { id: "mission-control", label: "Mission Control", icon: LayoutDashboard },
  { id: "chat", label: "Chat", icon: MessageSquare },
  { id: "student", label: "Student Hub", icon: GraduationCap },
  { id: "agents", label: "Agents", icon: Users },
  { id: "drafts", label: "Workflows", icon: FileText },
  { id: "projects", label: "Projects", icon: FolderKanban },
  { id: "memory", label: "Memory", icon: BrainCircuit },
  { id: "files", label: "Files", icon: FileText },
  { id: "integrations", label: "Integrations", icon: Puzzle },
  { id: "settings", label: "Settings", icon: Settings },
]

export const getAgent = (id: string) => ceaserAgents.find((agent) => agent.id === id)
export const getEngine = (id: string) => ceaserEngines.find((engine) => engine.id === id)
export const getPageTitle = (id: string) => navigationItems.find((item) => item.id === id)?.label ?? "Mission Control"
