from __future__ import annotations

from sqlalchemy import or_
from sqlalchemy.orm import Session

from app.intelligence.knowledge.models import ContextItem, ContextKind
from app.intelligence.orchestrator.models import ProviderPlan, RequestContext
from app.intelligence.providers.base import KnowledgeProvider
from app.models.conversation import Message
from app.models.file import File
from app.models.generated_document import GeneratedDocument
from app.models.memory import Memory
from app.models.project import Project


def _terms(query: str) -> list[str]:
    return [term.strip() for term in query.split() if len(term.strip()) > 2][:8]


class MemoryProvider(KnowledgeProvider):
    name = "memory"

    def __init__(self, db: Session) -> None:
        self.db = db

    async def retrieve(self, *, request: RequestContext, plan: ProviderPlan) -> list[ContextItem]:
        memories = self.db.query(Memory).filter(Memory.user_id == request.user_id).order_by(Memory.created_at.desc()).limit(plan.limit * 3).all()
        query_terms = _terms(plan.query.lower())
        filtered = [memory for memory in memories if not query_terms or any(term in memory.content.lower() for term in query_terms)]
        return [
            ContextItem(
                id=memory.id,
                provider=self.name,
                kind=ContextKind.MEMORY,
                title=memory.memory_type,
                content=memory.content,
                relevance_score=0.7,
                metadata=memory.extra_metadata,
                permissions=["read"],
            )
            for memory in filtered[: plan.limit]
        ]


class ProjectProvider(KnowledgeProvider):
    name = "projects"

    def __init__(self, db: Session) -> None:
        self.db = db

    async def retrieve(self, *, request: RequestContext, plan: ProviderPlan) -> list[ContextItem]:
        db_query = self.db.query(Project).filter(Project.user_id == request.user_id)
        if request.project_id:
            db_query = db_query.filter(Project.id == request.project_id)
        else:
            terms = _terms(plan.query)
            if terms:
                db_query = db_query.filter(or_(*[Project.name.ilike(f"%{term}%") for term in terms]))
        projects = db_query.order_by(Project.created_at.desc()).limit(plan.limit).all()
        return [
            ContextItem(
                id=project.id,
                provider=self.name,
                kind=ContextKind.PROJECT,
                title=project.name,
                content=f"{project.name}\nStatus: {project.status}\n{project.description or ''}".strip(),
                source_id=project.id,
                relevance_score=0.8 if request.project_id == project.id else 0.6,
                metadata={"status": project.status},
                permissions=["read"],
            )
            for project in projects
        ]


class ConversationProvider(KnowledgeProvider):
    name = "conversation"

    def __init__(self, db: Session) -> None:
        self.db = db

    async def retrieve(self, *, request: RequestContext, plan: ProviderPlan) -> list[ContextItem]:
        if not request.conversation_id:
            return []
        messages = (
            self.db.query(Message)
            .filter(Message.conversation_id == request.conversation_id)
            .order_by(Message.created_at.desc())
            .limit(plan.limit)
            .all()
        )
        return [
            ContextItem(
                id=message.id,
                provider=self.name,
                kind=ContextKind.MEMORY,
                title=f"{message.role} message",
                content=message.content,
                source_id=request.conversation_id,
                relevance_score=0.65,
                metadata={"role": message.role},
                permissions=["read"],
            )
            for message in messages
        ]


class GeneratedArtifactProvider(KnowledgeProvider):
    name = "generated_artifacts"

    def __init__(self, db: Session) -> None:
        self.db = db

    async def retrieve(self, *, request: RequestContext, plan: ProviderPlan) -> list[ContextItem]:
        records = (
            self.db.query(GeneratedDocument)
            .filter(GeneratedDocument.user_id == request.user_id)
            .order_by(GeneratedDocument.created_at.desc())
            .limit(plan.limit)
            .all()
        )
        return [
            ContextItem(
                id=record.id,
                provider=self.name,
                kind=ContextKind.GENERATED_ARTIFACT,
                title=f"{record.export_format.upper()} generated by {record.agent_id}",
                content=record.source_prompt,
                source_id=record.file_id,
                relevance_score=0.55,
                metadata={"file_id": record.file_id, "agent_id": record.agent_id, "template_id": record.template_id},
                permissions=["read"],
            )
            for record in records
        ]


class FileMetadataProvider(KnowledgeProvider):
    name = "files"

    def __init__(self, db: Session) -> None:
        self.db = db

    async def retrieve(self, *, request: RequestContext, plan: ProviderPlan) -> list[ContextItem]:
        db_query = self.db.query(File).filter(File.user_id == request.user_id)
        if request.project_id:
            db_query = db_query.filter(File.project_id == request.project_id)
        terms = _terms(plan.query)
        if terms:
            db_query = db_query.filter(or_(*[File.name.ilike(f"%{term}%") for term in terms]))
        files = db_query.order_by(File.created_at.desc()).limit(plan.limit).all()
        return [
            ContextItem(
                id=file.id,
                provider=self.name,
                kind=ContextKind.FILE,
                title=file.name,
                content=f"{file.name} ({file.file_type})",
                source_id=file.id,
                source_uri=file.storage_path,
                relevance_score=0.65,
                metadata={"file_type": file.file_type, "project_id": file.project_id},
                permissions=["read"],
            )
            for file in files
        ]

