from __future__ import annotations


AUTOMATION_TEMPLATES = [
    {
        "id": "daily-research-brief",
        "name": "Daily Research Brief",
        "category": "research",
        "description": "Nova researches important updates and creates a concise daily brief.",
        "default_agent": "nova",
        "default_prompt": "Create a concise daily research brief with 5 key updates, sources when available, 3 implications, and 2 next actions.",
        "supported_frequencies": ["daily", "every_weekday", "weekly"],
        "icon": "search",
    },
    {
        "id": "weekly-competitor-watch",
        "name": "Weekly Competitor Watch",
        "category": "research",
        "description": "Track competitors and summarize notable market movement.",
        "default_agent": "nova",
        "default_prompt": "Prepare a short competitor watch with 5 notable moves, source names when available, and 3 strategic implications.",
        "supported_frequencies": ["weekly", "monthly"],
        "icon": "radar",
    },
    {
        "id": "market-trend-report",
        "name": "Market Trend Report",
        "category": "research",
        "description": "Monitor industry trends and turn them into useful intelligence.",
        "default_agent": "nova",
        "default_prompt": "Generate a focused market trend brief with 5 trends, evidence, 3 risks, and 3 recommendations.",
        "supported_frequencies": ["weekly", "monthly"],
        "icon": "trending-up",
    },
    {
        "id": "source-monitoring",
        "name": "Source Monitoring",
        "category": "research",
        "description": "Review selected source themes and capture useful changes.",
        "default_agent": "nova",
        "default_prompt": "Monitor the configured topic and summarize only important changes with citations.",
        "supported_frequencies": ["daily", "weekly", "custom"],
        "icon": "rss",
    },
    {
        "id": "file-knowledge-digest",
        "name": "File Knowledge Digest",
        "category": "research",
        "description": "Digest uploaded files and turn them into useful takeaways.",
        "default_agent": "nova",
        "default_prompt": "Review recent files and create a compact digest with 5 insights and 3 action items.",
        "supported_frequencies": ["once", "daily", "weekly"],
        "icon": "files",
    },
    {
        "id": "daily-news-reader",
        "name": "Daily News Reader",
        "category": "news",
        "description": "Nova reads the latest important news and creates a concise daily briefing.",
        "default_agent": "nova",
        "default_prompt": "Create a concise daily news briefing with 5 top headlines, source names, one-line summaries, and 2 follow-ups.",
        "supported_frequencies": ["daily", "every_weekday", "weekly"],
        "icon": "newspaper",
    },
    {
        "id": "ai-news-digest",
        "name": "AI News Digest",
        "category": "news",
        "description": "Track AI news and summarize important model, product, startup, and policy updates.",
        "default_agent": "nova",
        "default_prompt": "Research latest AI news and create a short digest with 5 headlines, source-backed summaries, 3 implications, and 2 next actions.",
        "supported_frequencies": ["daily", "every_weekday", "weekly"],
        "icon": "sparkles",
    },
    {
        "id": "startup-news-radar",
        "name": "Startup News Radar",
        "category": "news",
        "description": "Monitor startup and funding news for useful opportunities and signals.",
        "default_agent": "nova",
        "default_prompt": "Research startup news and funding updates, then produce a radar brief with 5 signals, source names, and 3 opportunities.",
        "supported_frequencies": ["daily", "weekly"],
        "icon": "radar",
    },
    {
        "id": "healthtech-news-brief",
        "name": "HealthTech News Brief",
        "category": "news",
        "description": "Read healthtech news and turn it into a short actionable briefing.",
        "default_agent": "nova",
        "default_prompt": "Research latest healthtech news and create a short brief with 5 stories, source names, market implications, and 2 recommended actions.",
        "supported_frequencies": ["daily", "weekly"],
        "icon": "heart-pulse",
    },
    {
        "id": "daily-strategy-insight",
        "name": "Daily Strategy Insight",
        "category": "business",
        "description": "Zeus creates a focused strategic insight for the day.",
        "default_agent": "zeus",
        "default_prompt": "Create one daily strategy insight with 3 signals, 3 recommended moves, and 2 risks.",
        "supported_frequencies": ["daily", "every_weekday"],
        "icon": "briefcase",
    },
    {
        "id": "weekly-business-review",
        "name": "Weekly Business Review",
        "category": "business",
        "description": "Review progress, risks, and opportunities every week.",
        "default_agent": "zeus",
        "default_prompt": "Create a compact weekly business review with progress, blockers, opportunities, and 3 recommended decisions.",
        "supported_frequencies": ["weekly"],
        "icon": "bar-chart",
    },
    {
        "id": "revenue-model-review",
        "name": "Revenue Model Review",
        "category": "business",
        "description": "Evaluate revenue model assumptions and improvement options.",
        "default_agent": "zeus",
        "default_prompt": "Review the revenue model and give 3 improvements, 2 experiments, and 2 risks.",
        "supported_frequencies": ["weekly", "monthly"],
        "icon": "coins",
    },
    {
        "id": "go-to-market-review",
        "name": "Go-To-Market Review",
        "category": "business",
        "description": "Review launch channels, messaging, and next moves.",
        "default_agent": "zeus",
        "default_prompt": "Review go-to-market progress and create 3 prioritized recommendations.",
        "supported_frequencies": ["weekly", "monthly"],
        "icon": "rocket",
    },
    {
        "id": "investor-readiness-check",
        "name": "Investor Readiness Check",
        "category": "business",
        "description": "Check investor readiness and preparation gaps.",
        "default_agent": "zeus",
        "default_prompt": "Assess investor readiness with 3 gaps, 3 proof points, and 3 preparation tasks.",
        "supported_frequencies": ["weekly", "monthly"],
        "icon": "badge-dollar-sign",
    },
    {
        "id": "daily-linkedin-ideas",
        "name": "Daily LinkedIn Ideas",
        "category": "content",
        "description": "Friday generates useful LinkedIn post ideas.",
        "default_agent": "friday",
        "default_prompt": "Create 5 daily LinkedIn post ideas with hook, angle, and one short suggested post.",
        "supported_frequencies": ["daily", "every_weekday"],
        "icon": "message-square",
    },
    {
        "id": "weekly-content-calendar",
        "name": "Weekly Content Calendar",
        "category": "content",
        "description": "Plan a weekly content calendar.",
        "default_agent": "friday",
        "default_prompt": "Build a weekly content calendar with 5 slots, each with topic, format, channel, and goal.",
        "supported_frequencies": ["weekly"],
        "icon": "calendar",
    },
    {
        "id": "youtube-planner",
        "name": "YouTube Planner",
        "category": "content",
        "description": "Plan YouTube topics and outlines.",
        "default_agent": "friday",
        "default_prompt": "Create 5 YouTube video ideas with title, short outline, thumbnail angle, and priority.",
        "supported_frequencies": ["weekly", "monthly"],
        "icon": "play-square",
    },
    {
        "id": "campaign-planner",
        "name": "Campaign Planner",
        "category": "content",
        "description": "Plan campaign messaging and assets.",
        "default_agent": "friday",
        "default_prompt": "Create a compact campaign plan with audience, message, 5 assets, 3 schedule slots, and success metrics.",
        "supported_frequencies": ["once", "weekly"],
        "icon": "megaphone",
    },
    {
        "id": "content-repurposing",
        "name": "Content Repurposing",
        "category": "content",
        "description": "Turn existing ideas into multiple content formats.",
        "default_agent": "friday",
        "default_prompt": "Repurpose recent ideas into 5 content assets across posts, scripts, newsletters, and short-form content.",
        "supported_frequencies": ["weekly", "monthly"],
        "icon": "repeat",
    },
    {
        "id": "daily-study-plan",
        "name": "Daily Study Plan",
        "category": "learning",
        "description": "Alex creates a study plan for today.",
        "default_agent": "alex",
        "default_prompt": "Create today's study plan with 3-5 time blocks, 3 revision points, and 3 practice tasks.",
        "supported_frequencies": ["daily", "every_weekday"],
        "icon": "graduation-cap",
    },
    {
        "id": "weekly-learning-review",
        "name": "Weekly Learning Review",
        "category": "learning",
        "description": "Review learning progress and plan next improvements.",
        "default_agent": "alex",
        "default_prompt": "Create a compact weekly learning review with progress, 3 weak areas, and 3 study priorities.",
        "supported_frequencies": ["weekly"],
        "icon": "book-open",
    },
    {
        "id": "habit-check-in",
        "name": "Habit Check-In",
        "category": "learning",
        "description": "Review habits and suggest improvements.",
        "default_agent": "alex",
        "default_prompt": "Review habit progress and suggest 3 realistic adjustments for the next cycle.",
        "supported_frequencies": ["daily", "weekly"],
        "icon": "check-circle",
    },
    {
        "id": "exam-preparation",
        "name": "Exam Preparation",
        "category": "learning",
        "description": "Create exam preparation priorities and revision guidance.",
        "default_agent": "alex",
        "default_prompt": "Create a short exam prep plan with revision topics, 3 practice tasks, and weak-area focus.",
        "supported_frequencies": ["daily", "weekly"],
        "icon": "clipboard-check",
    },
    {
        "id": "goal-progress-review",
        "name": "Goal Progress Review",
        "category": "learning",
        "description": "Review goals and keep progress moving.",
        "default_agent": "alex",
        "default_prompt": "Review goal progress, identify 3 blockers, and create 3 practical next steps.",
        "supported_frequencies": ["weekly", "monthly"],
        "icon": "target",
    },
    {
        "id": "daily-task-planner",
        "name": "Daily Task Planner",
        "category": "execution",
        "description": "Bolt creates a practical task plan for the day.",
        "default_agent": "bolt",
        "default_prompt": "Create today's execution plan with 5 priorities, deadlines/dependencies when known, and 3 follow-ups.",
        "supported_frequencies": ["daily", "every_weekday"],
        "icon": "list-checks",
    },
    {
        "id": "follow-up-reminder",
        "name": "Follow-Up Reminder",
        "category": "execution",
        "description": "Review likely follow-ups and reminders.",
        "default_agent": "bolt",
        "default_prompt": "Review recent context and create up to 5 follow-up reminders with priority and timing.",
        "supported_frequencies": ["daily", "weekly"],
        "icon": "bell",
    },
    {
        "id": "weekly-execution-review",
        "name": "Weekly Execution Review",
        "category": "execution",
        "description": "Review execution progress and operational blockers.",
        "default_agent": "bolt",
        "default_prompt": "Create a compact weekly execution review with completed work, blocked work, risks, and 3 next actions.",
        "supported_frequencies": ["weekly"],
        "icon": "activity",
    },
    {
        "id": "project-roadmap-review",
        "name": "Project Roadmap Review",
        "category": "execution",
        "description": "Review roadmap progress and adjust priorities.",
        "default_agent": "bolt",
        "default_prompt": "Review the project roadmap and suggest 3 priority changes, milestones, and next steps.",
        "supported_frequencies": ["weekly", "monthly"],
        "icon": "map",
    },
    {
        "id": "deadline-reminder",
        "name": "Deadline Reminder",
        "category": "execution",
        "description": "Find upcoming deadlines and prepare a reminder brief.",
        "default_agent": "bolt",
        "default_prompt": "Review deadlines and prepare a short reminder brief with urgency and next actions.",
        "supported_frequencies": ["daily", "weekly"],
        "icon": "alarm-clock",
    },
    {
        "id": "technical-roadmap-review",
        "name": "Technical Roadmap Review",
        "category": "engineering",
        "description": "Atlas reviews technical roadmap priorities.",
        "default_agent": "atlas",
        "default_prompt": "Review technical roadmap priorities and identify architecture, dependency, and delivery risks in a compact brief.",
        "supported_frequencies": ["weekly", "monthly"],
        "icon": "code-2",
    },
    {
        "id": "architecture-review",
        "name": "Architecture Review",
        "category": "engineering",
        "description": "Review architecture decisions and technical risk.",
        "default_agent": "atlas",
        "default_prompt": "Create a short architecture review with 3 design risks, 3 tradeoffs, and 3 next decisions.",
        "supported_frequencies": ["weekly", "monthly"],
        "icon": "network",
    },
    {
        "id": "code-planning-review",
        "name": "Code Planning Review",
        "category": "engineering",
        "description": "Plan upcoming technical implementation work.",
        "default_agent": "atlas",
        "default_prompt": "Create a code planning review with 5 implementation steps, 3 risks, and dependencies. Do not write or execute code.",
        "supported_frequencies": ["once", "weekly"],
        "icon": "git-branch",
    },
    {
        "id": "project-structure-review",
        "name": "Project Structure Review",
        "category": "engineering",
        "description": "Review technical project structure and documentation.",
        "default_agent": "atlas",
        "default_prompt": "Review project structure and documentation needs, then suggest 5 lightweight improvements.",
        "supported_frequencies": ["weekly", "monthly"],
        "icon": "folder-tree",
    },
    {
        "id": "build-readiness-check",
        "name": "Build Readiness Check",
        "category": "engineering",
        "description": "Check readiness before a technical release.",
        "default_agent": "atlas",
        "default_prompt": "Create a build readiness checklist with quality, testing, release, and documentation items.",
        "supported_frequencies": ["once", "weekly"],
        "icon": "shield-check",
    },
]


class AutomationTemplateRegistry:
    def list(self) -> list[dict]:
        return [dict(template, is_active=True) for template in AUTOMATION_TEMPLATES]

    def grouped(self) -> dict[str, list[dict]]:
        groups: dict[str, list[dict]] = {}
        for template in self.list():
            groups.setdefault(template["category"], []).append(template)
        return groups

    def get(self, template_id: str) -> dict | None:
        return next((template for template in self.list() if template["id"] == template_id), None)
